### PR TITLE
proper implementation of Parse.Cloud.httpRequest

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by flovilmart** [comment]
Taken from http://github.com/flovilmart/parse-cloud that I've been using for 3 years to run parse servers locally :)

**Comment by gfosco** [comment]
Still valuable?  If so, can you rebase?

**Comment by flovilmart** [comment]
@gfosco there is a new and adapted implementation based on `request` in parse-server. Should we use the one from here then?

**Comment by gfosco** [comment]
Whichever you think is more appropriate... I trust your judgment on that.

**Comment by flovilmart** [comment]
because this will be a dependency in the multi-app support, I believe it's better to centralize the code base in there. Or to dump that repo altogether an provide the full implementation on parse-server

**Comment by gfosco** [comment]
I think people should only be using parse-cloud-express in a webhooks situation, not with parse-server.. right?...  If parse-server could also support webhooks, I'd be okay with that too.

**Comment by flovilmart** [comment]
That's why I integrated it with parse-server. 
The only 'good' way to come around the shared memory state was to.... spawn a new process. So I'm using the 'new' hooks API (just POST for now, overrides all preexisting hooks) to auto register the hooks, wrapped around the parse-cloud-express server hooks :).
The good thing is that it give a proper isolated cloud code environment, that don't share the server state, which is safer, and allows to spawn on external servers (already integrated and tested). and yes that's a big chunk

**Comment by flovilmart** [comment]
@gfosco you can merge if you want to! That won't hurt anyone.

**Pull request merged**
